### ISSUE TITLE
Potential Scam ?

### ISSUE THREAD

**Issue by the4ndy** [norbertvdberg/iotaseed#3]
Looks like this github was linked and referenced in a recent discussion on Reddit. Without passing judgement, it appears as though a user is accusing this application as being fake / a scam and indicates that it generates the key in such a way (they say the same every time) that allows the creator of this application to steal their crypto currency.  
  
This issue is being posted as a WARNING. I am not casting judgement in either direction, the link to the discussion is below, please be careful and always do your own research.  
  
https://www.reddit.com/r/Iota/comments/6ytm9v/i_got_hacked_right_after_creating_a_wallet/

**Comment by norbertvdberg** [comment]
I don't know how to bring this up, but first of all my sincerest apologies.

When making the site IE-proof (old IE's lack of support for splice, for Int32Array's), a bug was introduced which caused the entropy not to be recorded. It was in the repository for about a week. Luckily the live site seems to have been spared, as I had not synced it up there yet.

I have now updated the descriptions, and the running version of the site.

My sincerest apologies.

PS: It was not me who took the money from the seed, but probably someone who downloaded the repo code, and noticed the seed bug without reporting it. Shit, I feel really bad about this.

(also posted this in reply on the reddit thread)
